from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from ..api.dashboard_data import load_dataset
from ..storage import write_json_document


def is_record_malicious(record: dict[str, Any]) -> bool:
    threat_intel = record.get("threat_intel")
    if not isinstance(threat_intel, dict):
        return False

    score = threat_intel.get("score")
    if not isinstance(score, dict):
        return False

    return score.get("is_malicious") is True


def get_malicious_records(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [record for record in records if is_record_malicious(record)]


def collect_blocklist_ips(records: list[dict[str, Any]]) -> list[str]:
    ips = {
        record.get("source_ip")
        for record in get_malicious_records(records)
        if isinstance(record.get("source_ip"), str) and record.get("source_ip")
    }
    return sorted(ips)


def build_markdown_report(
    records: list[dict[str, Any]],
    summary: dict[str, Any],
    blocklist_ips: list[str],
) -> str:
    malicious_records = get_malicious_records(records)
    lines = [
        "# Honeypot Threat Intelligence Report",
        "",
        "## Summary",
        "",
        f"- Total events: {summary.get('total_events', 0)}",
        f"- Unique source IPs: {summary.get('unique_source_ips', 0)}",
        f"- Malicious events: {len(malicious_records)}",
        f"- Blocklist candidates: {len(blocklist_ips)}",
        "",
        "## Risk Levels",
        "",
    ]

    risk_levels = summary.get("by_risk_level", {})
    if isinstance(risk_levels, dict) and risk_levels:
        for key, value in risk_levels.items():
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "## Attack Categories",
            "",
        ]
    )

    categories = summary.get("by_attack_category", {})
    if isinstance(categories, dict) and categories:
        for key, value in categories.items():
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "## Blocklist Candidates",
            "",
        ]
    )

    if blocklist_ips:
        for ip in blocklist_ips:
            lines.append(f"- {ip}")
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "## Recent Malicious Events",
            "",
        ]
    )

    if malicious_records:
        for record in malicious_records[:10]:
            risk = record.get("risk") if isinstance(record.get("risk"), dict) else {}
            lines.append(
                f"- `{record.get('timestamp', '-')}` `{record.get('source_ip', '-')}` "
                f"`{record.get('event_type', '-')}` risk `{risk.get('level', 'unknown')}`"
            )
    else:
        lines.append("- none")

    lines.append("")
    return "\n".join(lines)


def export_report_bundle(records_file: Path, summary_file: Path | None, output_dir: Path) -> dict[str, Path]:
    dataset = load_dataset(records_file, summary_file)
    output_dir.mkdir(parents=True, exist_ok=True)

    malicious_records = get_malicious_records(dataset.records)
    blocklist_ips = collect_blocklist_ips(dataset.records)
    markdown_report = build_markdown_report(dataset.records, dataset.summary, blocklist_ips)

    malicious_records_path = output_dir / "malicious-records.json"
    blocklist_path = output_dir / "blocklist.txt"
    report_path = output_dir / "report.md"

    write_json_document(
        malicious_records_path,
        {
            "malicious_record_count": len(malicious_records),
            "records": malicious_records,
        },
    )
    blocklist_path.write_text("\n".join(blocklist_ips) + ("\n" if blocklist_ips else ""), encoding="utf-8")
    report_path.write_text(markdown_report, encoding="utf-8")

    return {
        "malicious_records": malicious_records_path,
        "blocklist": blocklist_path,
        "report": report_path,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate safe action outputs and a report from processed honeypot records."
    )
    parser.add_argument(
        "--records-file",
        type=Path,
        required=True,
        help="Path to the processed JSONL event records file.",
    )
    parser.add_argument(
        "--summary-file",
        type=Path,
        help="Optional path to the JSON summary file generated by the pipeline.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory where the report bundle should be written.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if not args.records_file.exists():
        parser.error(f"Records file not found: {args.records_file}")

    outputs = export_report_bundle(args.records_file, args.summary_file, args.output_dir)
    print(json.dumps({key: str(value) for key, value in outputs.items()}, ensure_ascii=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
