"""Automated incident response: firewall blocklist management.

Safe by default — all operations are dry-run unless ``apply=True`` is
explicitly passed.  Designed for lab environments where the pipeline
operator reviews blocklist candidates before enforcing them.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path
from typing import Any

from ..api.dashboard_data import load_dataset
from ..reporting import collect_blocklist_ips
from ..settings import Settings
from ..storage.database import Database


class FirewallManager:
    """Manage iptables rules for honeypot blocklist enforcement.

    All mutating operations default to *dry_run=True*.  Pass
    ``apply=True`` only after reviewing the generated rules.
    """

    def __init__(
        self,
        chain: str = "INPUT",
        apply: bool = False,
        table: str = "filter",
        comment_prefix: str = "honeypot-block",
    ) -> None:
        self.chain = chain
        self.apply = apply
        self.table = table
        self.comment_prefix = comment_prefix

    # ── Public API ──────────────────────────────────────────────────────

    def build_rules(self, ips: list[str]) -> list[dict[str, str]]:
        """Return the iptables commands that *would* be executed.

        Each result is a dict with ``ip`` and ``command`` keys.
        """
        rules: list[dict[str, str]] = []
        existing = self._list_blocked_ips()

        for ip in sorted(set(ips)):
            if ip in existing:
                rules.append({"ip": ip, "command": "# already blocked — skipped"})
                continue
            cmd = (
                f"iptables -A {self.chain} "
                f"-s {ip} "
                f"-m comment --comment \"{self.comment_prefix}\" "
                f"-j DROP"
            )
            rules.append({"ip": ip, "command": cmd})

        return rules

    def block_ips(self, ips: list[str]) -> list[dict[str, str]]:
        """Generate and optionally apply iptables DROP rules for *ips*."""
        rules = self.build_rules(ips)

        if not self.apply:
            return rules

        applied: list[dict[str, str]] = []
        for rule in rules:
            if rule["command"].startswith("#"):
                applied.append(rule)
                continue

            ip = rule["ip"]
            if not self._rule_exists(ip):
                subprocess.run(
                    [
                        "iptables", "-A", self.chain,
                        "-s", ip,
                        "-m", "comment", "--comment", self.comment_prefix,
                        "-j", "DROP",
                    ],
                    check=True,
                )
                applied.append({"ip": ip, "command": f"iptables -A {self.chain} -s {ip} ... -j DROP  # APPLIED"})
            else:
                applied.append({"ip": ip, "command": "# already blocked — skipped"})

        return applied

    def unblock_ips(self, ips: list[str]) -> list[dict[str, str]]:
        """Remove iptables DROP rules for *ips*."""
        removed: list[dict[str, str]] = []
        existing = self._list_blocked_ips()

        for ip in sorted(set(ips)):
            if ip not in existing:
                removed.append({"ip": ip, "command": "# not blocked — skipped"})
                continue

            if self.apply:
                subprocess.run(
                    [
                        "iptables", "-D", self.chain,
                        "-s", ip,
                        "-m", "comment", "--comment", self.comment_prefix,
                        "-j", "DROP",
                    ],
                    check=True,
                )
                removed.append({"ip": ip, "command": f"iptables -D {self.chain} -s {ip} ... -j DROP  # REMOVED"})
            else:
                removed.append({
                    "ip": ip,
                    "command": f"iptables -D {self.chain} -s {ip} -m comment --comment \"{self.comment_prefix}\" -j DROP",
                })

        return removed

    def list_blocks(self) -> list[str]:
        """Return IPs currently blocked by this tool."""
        return sorted(self._list_blocked_ips())

    def generate_script(self, ips: list[str]) -> str:
        """Build a standalone shell script that applies the blocklist."""
        rules = self.build_rules(ips)
        lines = [
            "#!/usr/bin/env bash",
            "# Auto-generated by honeypot-pipeline response module",
            "# Review before running: this script requires root.",
            "#",
            "# Dry-run: bash blocklist.sh --dry-run",
            "# Apply:    sudo bash blocklist.sh",
            "",
            "set -euo pipefail",
            "",
            'CHAIN="${CHAIN:-INPUT}"',
            "",
        ]

        if any(not r["command"].startswith("#") for r in rules):
            lines.append("echo 'Applying honeypot blocklist...'")
            for rule in rules:
                cmd = rule["command"]
                if cmd.startswith("#"):
                    lines.append(f"echo '{cmd}'")
                else:
                    ip = rule["ip"]
                    # Use iptables -C to check before -A
                    lines.append(
                        f"if ! iptables -C $CHAIN -s {ip} -j DROP 2>/dev/null; then\n"
                        f"    iptables -A $CHAIN -s {ip} "
                        f'-m comment --comment "honeypot-block" -j DROP\n'
                        f"    echo '  BLOCKED {ip}'\n"
                        f"else\n"
                        f"    echo '  SKIPPED {ip} (already blocked)'\n"
                        f"fi"
                    )
            lines.append("echo 'Done.'")
        else:
            lines.append("echo 'All IPs are already blocked. Nothing to do.'")

        return "\n".join(lines) + "\n"

    # ── Internal helpers ─────────────────────────────────────────────────

    def _rule_exists(self, ip: str) -> bool:
        """Check if a DROP rule for *ip* already exists in the chain."""
        try:
            result = subprocess.run(
                [
                    "iptables", "-C", self.chain,
                    "-s", ip,
                    "-m", "comment", "--comment", self.comment_prefix,
                    "-j", "DROP",
                ],
                capture_output=True,
                timeout=5,
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _list_blocked_ips(self) -> set[str]:
        """Parse iptables -L output for IPs blocked with our comment tag."""
        try:
            result = subprocess.run(
                ["iptables", "-L", self.chain, "-n", "--line-numbers"],
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return set()

        ips: set[str] = set()
        for line in result.stdout.splitlines():
            if self.comment_prefix not in line or "DROP" not in line:
                continue
            # iptables -L -n columns: num target prot opt source destination [extras]
            parts = line.split()
            # Find source IP (column before destination, which is 0.0.0.0/0)
            for i, part in enumerate(parts):
                if re.match(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$", part) and i > 0:
                    # Skip destination (0.0.0.0/0 or similar any-address)
                    if part == "0.0.0.0":
                        continue
                    ips.add(part)
                    break  # only the first real IP (source)

        return ips


# ── CLI helpers ────────────────────────────────────────────────────────────


def _resolve_blocklist_ips(
    records_file: Path | None = None,
    db_path: Path | None = None,
    malicious_only: bool = False,
) -> list[str]:
    """Collect blocklist IPs from JSONL records or database."""

    if db_path is not None and db_path.exists():
        db = Database(db_path)
        db.initialize()
        records, _ = db.query_events(malicious_only=malicious_only)
        db.close()
        return collect_blocklist_ips(records)

    if records_file is not None and records_file.exists():
        dataset = load_dataset(records_file)
        if malicious_only:
            from ..reporting import get_malicious_records
            records = get_malicious_records(dataset.records)
        else:
            records = dataset.records
        return collect_blocklist_ips(records)

    return []


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Apply or review iptables blocklist rules from pipeline output."
    )
    parser.add_argument(
        "--records-file",
        type=Path,
        help="Path to the processed JSONL event records file.",
    )
    parser.add_argument(
        "--db",
        type=Path,
        help="SQLite database path (reads blocklist from there if available).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=True,
        help="Print rules without applying them (default).",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually apply iptables rules. Requires root. Bypasses --dry-run.",
    )
    parser.add_argument(
        "--unblock",
        action="store_true",
        help="Remove previously applied blocklist rules instead of adding them.",
    )
    parser.add_argument(
        "--chain",
        default="INPUT",
        help="iptables chain to target (default: INPUT).",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List currently blocked IPs and exit.",
    )
    parser.add_argument(
        "--generate-script",
        type=Path,
        help="Write a standalone shell script to this path instead of taking action.",
    )
    parser.add_argument(
        "--ip",
        action="append",
        help="Block a specific IP directly (repeatable). Overrides file/db sources.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    mgr = FirewallManager(
        chain=args.chain,
        apply=args.apply,
    )

    # --list mode
    if args.list:
        blocked = mgr.list_blocks()
        if blocked:
            for ip in blocked:
                print(ip)
        else:
            print("# No honeypot-block rules found.")
        return 0

    # Resolve IPs
    if args.ip:
        ips = list(args.ip)
    else:
        settings = Settings.from_env()
        db_path = args.db or (Path(settings.database_url) if Path(settings.database_url).exists() else None)
        ips = _resolve_blocklist_ips(
            records_file=args.records_file,
            db_path=db_path,
        )

    if not ips:
        print("No IPs to block. Run the pipeline first to populate the blocklist.")
        return 0

    # --generate-script mode
    if args.generate_script:
        script = mgr.generate_script(ips)
        args.generate_script.write_text(script, encoding="utf-8")
        args.generate_script.chmod(0o755)
        print(f"Script written to {args.generate_script}")
        print(f"  Review it, then run: sudo bash {args.generate_script}")
        return 0

    # --unblock mode
    if args.unblock:
        results = mgr.unblock_ips(ips)
        for r in results:
            print(r["command"])
        return 0

    # Default: block
    results = mgr.block_ips(ips)

    if args.apply:
        applied_count = sum(1 for r in results if "APPLIED" in r["command"])
        skipped_count = sum(1 for r in results if "skipped" in r["command"])
        print(f"Blocked {applied_count} IPs ({skipped_count} already blocked).")
    else:
        print("# DRY RUN — no rules applied. Use --apply to enforce.\n")
        for r in results:
            print(r["command"])
        print(f"\n# {len(ips)} IP(s) would be blocked.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
